spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Let Hibernate create schema from @Entity classes
spring.jpa.hibernate.ddl-auto=create
# Ensure consistent DB name
spring.datasource.generate-unique-name=false
# Run custom SQL file at startup
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:rewardPointsData.sql
spring.jpa.defer-datasource-initialization=true

